compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_multinode_launcher: standard
  gradient_accumulation_steps: 1
  offload_optimizer_device: none
  offload_param_device: cpu 
  zero3_init_flag: True
  zero_stage: 3
distributed_type: DEEPSPEED 
downcast_bf16: 'no'
dynamo_config:
  dynamo_backend: INDUCTOR
machine_rank: 0
main_process_ip: 52.68.90.164
main_process_port: 12355
main_training_function: main
mixed_precision: fp16 
num_machines: 2
num_processes: 2
rdzv_backend: static
same_network: false
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
